# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/tree/master/Resources/doc/index.md
oneup_flysystem:
    adapters:
        public_uploads_adapter:
            local:
                directory: '%kernel.cache_dir%/public/images/gallery'
    filesystems:
        public_filesystem:
            adapter: public_uploads_adapter
